CREATE TABLE [dbo].[ClientesMovimiento] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [IdCliente]              UNIQUEIDENTIFIER NOT NULL,
    [IdTipoComprobante]      INT              NULL,
    [IdComprobante]          UNIQUEIDENTIFIER NULL,
    [Concepto]               NVARCHAR (50)    NULL,
    [Debe]                   MONEY            NULL,
    [Haber]                  MONEY            NULL,
    [Observaciones]          NVARCHAR (100)   NULL,
    [FechaGeneracion]        DATETIME         NULL,
    [FechaAlta]              DATETIME         NULL,
    [SucursalAltaId]         INT              NULL,
    [OperadorAltaId]         UNIQUEIDENTIFIER NULL,
    [FechaModificacion]      DATETIME         NULL,
    [SucursalModificacionId] INT              NULL,
    [OperadorModificacionId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_ClientesMovimiento_1] PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_ClientesMovimiento_Clientes] FOREIGN KEY (IdCliente) REFERENCES Clientes(Id), 
    CONSTRAINT [FK_ClientesMovimiento_TipoComprobante] FOREIGN KEY (IdTipoComprobante) REFERENCES TiposComprobantes(Id), 
    CONSTRAINT [FK_ClientesMovimiento_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_ClientesMovimiento_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_ClientesMovimiento_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_ClientesMovimiento_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id)
);