CREATE TABLE [dbo].[MovilesMontoFavor]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [MovilId] UNIQUEIDENTIFIER NOT NULL,
	[FechaComprobante] [smalldatetime] NOT NULL,
	[TipoComprobanteId] [int] NOT NULL,
	[Concepto] [nvarchar](50) NULL,
	[Importe] [money] NULL,
	[ImpOcupado] [money] NULL,
	[FechaAnulacion] [datetime] NULL,
	[OperadorAutorizaId] [uniqueidentifier] NULL,
	[Observaciones] [nvarchar](90) NULL,
	[FechaAlta] [datetime] NOT NULL,
	[SucursalAltaId] [int] NOT NULL,
	[OperadorAltaId] [uniqueidentifier] NOT NULL,
	[FechaModificacion] [datetime] NULL,
	[SucursalModificacionId] [int] NULL,
	[OperadorModificacionId] [uniqueidentifier] NULL, 
    CONSTRAINT [FK_MovilesMontoFavor_Movil] FOREIGN KEY (MovilId) REFERENCES Moviles(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_TipoComprobante] FOREIGN KEY (TipoComprobanteId) REFERENCES TiposComprobantes(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_OperadorAutoriza] FOREIGN KEY (OperadorAutorizaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_SucursalAlta] FOREIGN KEY (SucursalAltaId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_OperadorAlta] FOREIGN KEY (OperadorAltaId) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_SucursalModificacion] FOREIGN KEY (SucursalModificacionId) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_MovilesMontoFavor_OperadorModificacion] FOREIGN KEY (OperadorModificacionId) REFERENCES Operadores(Id),
)
