CREATE TABLE [dbo].[Vales]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Numero] INT NOT NULL, 
    [MovilPresentaId] UNIQUEIDENTIFIER NOT NULL, 
    [MovilViajeId] UNIQUEIDENTIFIER NOT NULL, 
    [ClienteId] UNIQUEIDENTIFIER NOT NULL, 
    [FechaViaje] DATETIME NULL, 
    [Monto] DECIMAL NULL,     
    [Presentado] BIT NULL, 
    [Facturado] BIT NULL, 
    [Aprobado] BIT NULL,
	[FechaAlta] DATETIME NOT NULL, 
    [OperadorAlta] UNIQUEIDENTIFIER NOT NULL, 
    [SucursalAlta] INT NOT NULL, 
    [FechaModificacion] DATETIME NULL, 
    [OperadorModificacion] UNIQUEIDENTIFIER NULL, 
    [SucursalModificacion] INT NULL, 
    CONSTRAINT [FK_Vales_MovilPresenta] FOREIGN KEY (MovilPresentaId) REFERENCES Moviles(Id), 
    CONSTRAINT [FK_Vales_MovilViaje] FOREIGN KEY (MovilViajeId) REFERENCES Moviles(Id), 
    CONSTRAINT [FK_Vales_Cliente] FOREIGN KEY (ClienteId) REFERENCES Clientes(Id), 
    CONSTRAINT [FK_Vales_OperadorAlta] FOREIGN KEY (OperadorAlta) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_Vales_SucursalAlta] FOREIGN KEY (SucursalAlta) REFERENCES Sucursales(Id), 
    CONSTRAINT [FK_Vales_OperadorModificacion] FOREIGN KEY (OperadorModificacion) REFERENCES Operadores(Id), 
    CONSTRAINT [FK_Vales_SucursalModificacion] FOREIGN KEY (SucursalModificacion) REFERENCES Sucursales(Id), 

)
