//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celular
    {
        public Celular()
        {
            this.CelularesMovimiento = new HashSet<CelularMovimiento>();
            this.PagosCelular = new HashSet<PagoCelular>();
            this.Choferes = new HashSet<Chofer>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> TipoCelularId { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public Nullable<System.DateTime> Baja { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Pagare { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaProximoPago { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> DiaPagoId { get; set; }
        public Nullable<System.DateTime> FechaVencimientoPago { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> EmpresaCelular { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Imei { get; set; }
        public string SIM { get; set; }
        public string Email { get; set; }
        public Nullable<int> DiaCargaId { get; set; }
        public Nullable<int> ModeloCelularId { get; set; }
        public Nullable<int> NumeroPagare { get; set; }
    
        public virtual Dia DiaPago { get; set; }
        public virtual Operador Operadores { get; set; }
        public virtual Operador Operadores1 { get; set; }
        public virtual Sucursal Sucursales { get; set; }
        public virtual Sucursal Sucursales1 { get; set; }
        public virtual TipoCelular TiposCelulares { get; set; }
        public virtual ICollection<CelularMovimiento> CelularesMovimiento { get; set; }
        public virtual ICollection<PagoCelular> PagosCelular { get; set; }
        public virtual ICollection<Chofer> Choferes { get; set; }
        public virtual EmpresasCelulare EmpresasCelulare { get; set; }
        public virtual Dia DiaCarga { get; set; }
        public virtual ModelosCelulare ModelosCelulare { get; set; }
    }
}
