//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia
    {
        public Dia()
        {
            this.Celulares = new HashSet<Celular>();
            this.Celulares1 = new HashSet<Celular>();
            this.Moviles = new HashSet<Movil>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Celular> Celulares { get; set; }
        public virtual ICollection<Celular> Celulares1 { get; set; }
        public virtual ICollection<Movil> Moviles { get; set; }
    }
}
