//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosTallere
    {
        public MotivosTallere()
        {
            this.TalleresMoviles = new HashSet<TalleresMovile>();
        }
    
        public System.Guid Id { get; set; }
        public string Motivo { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<TalleresMovile> TalleresMoviles { get; set; }
    }
}
