//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movil
    {
        public Movil()
        {
            this.Choferes = new HashSet<Chofer>();
            this.ChoferesMovils = new HashSet<ChoferesMovil>();
            this.PagosCelulars = new HashSet<PagoCelular>();
            this.PagosMoviles = new HashSet<PagosMovile>();
            this.MovilesMontoFavors = new HashSet<MovilesMontoFavor>();
            this.TalleresMoviles = new HashSet<TalleresMovile>();
        }
    
        public System.Guid Id { get; set; }
        public int Numero { get; set; }
        public string Patente { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public int SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaProximoPago { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> DiaPago { get; set; }
        public Nullable<System.Guid> TitularId { get; set; }
    
        public virtual Operador Operadores { get; set; }
        public virtual Operador Operadores1 { get; set; }
        public virtual Sucursal Sucursales { get; set; }
        public virtual Sucursal Sucursales1 { get; set; }
        public virtual ICollection<Chofer> Choferes { get; set; }
        public virtual ICollection<ChoferesMovil> ChoferesMovils { get; set; }
        public virtual ICollection<PagoCelular> PagosCelulars { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual ICollection<PagosMovile> PagosMoviles { get; set; }
        public virtual ICollection<MovilesMontoFavor> MovilesMontoFavors { get; set; }
        public virtual ICollection<TalleresMovile> TalleresMoviles { get; set; }
        public virtual Titulare Titulare { get; set; }
    }
}
