//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPagoDetalle
    {
        public System.Guid Id { get; set; }
        public System.Guid OrdenPagoId { get; set; }
        public Nullable<int> NumeroLinea { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> ImportePagado { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheques { get; set; }
        public Nullable<decimal> Deposito { get; set; }
        public Nullable<decimal> DepositoEfectivo { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<decimal> Transferencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.Guid> CajaId { get; set; }
        public Nullable<System.Guid> OperadorAutorizaId { get; set; }
    
        public virtual Caja Cajas { get; set; }
        public virtual Operador Operadores { get; set; }
        public virtual Operador Operadores1 { get; set; }
        public virtual Operador Operadores2 { get; set; }
        public virtual OrdenPago OrdenesPago { get; set; }
        public virtual Sucursal Sucursales { get; set; }
        public virtual Sucursal Sucursales1 { get; set; }
    }
}
