//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalleresMovile
    {
        public TalleresMovile()
        {
            this.TalleresMotivosMoviles = new HashSet<TalleresMotivosMovile>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid TallerId { get; set; }
        public System.Guid MovilId { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaEstimativaHasta { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public int SucursalAltaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Acreditado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Operador Operadore { get; set; }
        public virtual Operador Operadore1 { get; set; }
        public virtual Sucursal Sucursale { get; set; }
        public virtual Sucursal Sucursale1 { get; set; }
        public virtual Movil Movil { get; set; }
        public virtual Tallere Tallere { get; set; }
        public virtual ICollection<TalleresMotivosMovile> TalleresMotivosMoviles { get; set; }
    }
}
