//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalleresMotivosMovile
    {
        public System.Guid Id { get; set; }
        public System.Guid TallerMovilId { get; set; }
        public System.Guid MotivoTallerId { get; set; }
    
        public virtual MotivosTallere MotivosTallere { get; set; }
        public virtual TalleresMovile TalleresMovile { get; set; }
    }
}
