//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoComprobante
    {
        public TipoComprobante()
        {
            this.CajasMovimientos = new HashSet<CajaMovimiento>();
            this.CelularesMovimiento = new HashSet<CelularMovimiento>();
            this.ChoferesMontosFavor = new HashSet<ChoferMontoFavor>();
            this.OrdenesPago = new HashSet<OrdenPago>();
            this.MovilesMontoFavors = new HashSet<MovilesMontoFavor>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Abreviatura { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Comprobante { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
    
        public virtual ICollection<CajaMovimiento> CajasMovimientos { get; set; }
        public virtual ICollection<CelularMovimiento> CelularesMovimiento { get; set; }
        public virtual ICollection<ChoferMontoFavor> ChoferesMontosFavor { get; set; }
        public virtual Operador Operadores { get; set; }
        public virtual Operador Operadores1 { get; set; }
        public virtual ICollection<OrdenPago> OrdenesPago { get; set; }
        public virtual Sucursal Sucursales { get; set; }
        public virtual Sucursal Sucursales1 { get; set; }
        public virtual ICollection<MovilesMontoFavor> MovilesMontoFavors { get; set; }
    }
}
