//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GestionAdministrativa.Entities;

namespace GestionAdministrativa.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionAdministrativaDbContext : DbContext
    {
        public GestionAdministrativaDbContext()
            : base("name=GestionAdministrativaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<CajaMovimiento> CajasMovimientos { get; set; }
        public virtual DbSet<CategoriaOperador> CategoriasOperadores { get; set; }
        public virtual DbSet<CelularMovimiento> CelularesMovimiento { get; set; }
        public virtual DbSet<CentroCosto> CentrosCostos { get; set; }
        public virtual DbSet<ChoferMontoFavor> ChoferesMontosFavor { get; set; }
        public virtual DbSet<Concepto> Conceptos { get; set; }
        public virtual DbSet<CondicionCompra> CondicionesCompra { get; set; }
        public virtual DbSet<Dia> Dias { get; set; }
        public virtual DbSet<Funcion> Funciones { get; set; }
        public virtual DbSet<GrupoProveedor> GruposProveedores { get; set; }
        public virtual DbSet<Localidad> Localidades { get; set; }
        public virtual DbSet<Movil> Moviles { get; set; }
        public virtual DbSet<Operador> Operadores { get; set; }
        public virtual DbSet<OperadorFuncion> OperadoresFunciones { get; set; }
        public virtual DbSet<OperadorSucursal> OperadoresSucursales { get; set; }
        public virtual DbSet<OrdenPago> OrdenesPago { get; set; }
        public virtual DbSet<OrdenPagoDetalle> OrdenesPagoDetalle { get; set; }
        public virtual DbSet<PagoCelular> PagosCelular { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Personal> Personales { get; set; }
        public virtual DbSet<PersonalConcepto> PersonalesConceptos { get; set; }
        public virtual DbSet<PersonalNovedad> PersonalNovedades { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
        public virtual DbSet<ProveedorBanco> ProveedoresBancos { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Recibo> Recibos { get; set; }
        public virtual DbSet<ReciboDetalle> RecibosDetalles { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Sucursal> Sucursales { get; set; }
        public virtual DbSet<TipoCelular> TiposCelulares { get; set; }
        public virtual DbSet<TipoComprobante> TiposComprobantes { get; set; }
        public virtual DbSet<TipoDocumentosIdentidad> TiposDocumentosIdentidad { get; set; }
        public virtual DbSet<TipoGasto> TiposGastos { get; set; }
        public virtual DbSet<TipoMovimientoCaja> TiposMovimientosCajas { get; set; }
        public virtual DbSet<TipoRecibo> TiposRecibos { get; set; }
        public virtual DbSet<Chofer> Choferes { get; set; }
        public virtual DbSet<EmpresasCelulare> EmpresasCelulares { get; set; }
        public virtual DbSet<ModelosCelulare> ModelosCelulares { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Celular> Celulares { get; set; }
    }
}
